services:
  builder:
    build:
      context: ..
      dockerfile: docker/Dockerfile.builder
    working_dir: /workspace
    volumes:
      - ..:/workspace
    command: >-
      bash -lc "npm ci && ./build.sh --yes --run-unit-tests && ./deploy.sh --yes"

  web:
    image: nginx:1.27-alpine
    depends_on:
      builder:
        condition: service_completed_successfully
    ports:
      - "8080:80"
    volumes:
      - ../.deployment/site:/usr/share/nginx/html:ro
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro

  web-image:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "8081:80"
    profiles:
      - image
